name: SQL Linter Check
on: [push]

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Run SQL Linter
        # Перевіряємо файл DataSchema.sql.
        run: sqlfluff lint DataSchema.sql --dialect ansi
