name: JavaScript Code Linter
on: [push]

jobs:
  JavaScriptCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Biome
        run: npm install --save-dev --save-exact @biomejs/biome

      - name: Run Biome Check
        # Перевіряємо наш файл
        run: npx @biomejs/biome check ProgramCode.js
